--- 
abstract: Splitting HTML text by number of characters.
author: 
  - Hiroshi Sakai <ziguzagu@cpan.org>
build_requires: 
  Class::Accessor::Fast: 0
  HTML::Parser: 0
  Test::Base: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: HTML-Split
no_index: 
  directory: 
    - inc
    - t
requires: 
  perl: 5.8.1
version: 0.01
